RDKCOM-382: add -pthread to rdkbPowerMgr LDFLAGS
 | /usr/src/debug/powermgr/2.1+gitAUTOINC+c3091d934e-r0/git/source/pwrMgr.c:350: error: undefined reference to 'pthread_create'
 | /usr/src/debug/powermgr/2.1+gitAUTOINC+c3091d934e-r0/git/source/pwrMgr.c:358: error: undefined reference to 'pthread_setname_np'
 | /usr/src/debug/powermgr/2.1+gitAUTOINC+c3091d934e-r0/git/source/pwrMgr.c:497: error: undefined reference to 'pthread_join'
 | collect2: error: ld returned 1 exit status
 | make[2]: *** [rdkbPowerMgr] Error 1
 | make[2]: Leaving directory `/.../build-qemux86broadband/tmp/work/i586-rdk-linux/powermgr/2.1+gitAUTOINC+c3091d934e-r0/build/source'
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: add -pthread to rdkbPowerMgr LDFLAGS
Test Procedure: None.
Risks: Low.

(cherry picked from commit 85a59a74be969a1972fd29b92378828f68797bc6)
(cherry picked from commit 00d5c9b59b15e50f69e82f77cc034674cda321f2)

Change-Id: Iff60327a93db427730e2f6741ec551d5715adf89